projects:

  fierry-performance:
    main:   performance/App.coffee
    source: [source, performance]
    libs:
      - /Code/JavaScript/jQuery/jquery-1.5.2.js

  fierry-example:
    main:   example/App.coffee 
    source: [source, example]
