function e(a){return function(){return a}}
var g=function(){var a={g:{},s:{},h:/^\?!/,e:0};a.d=function(b,c){if(a.h.test(b))throw Error('Module name is required not to start with "?!".');a.g[b]=c};a.r=-1;a.a=function(b){var c,d=a.r;return function(){if(d<a.e)d=a.e,c=a.m(a.b,b);return c}};a.j=function(b){return a.m(a.s,b)};a.t=function(){a.a("fierry-example/app")()};a.l={};a.p={};a.n={};a.m=function(b,c){var d=b[c];if(d!==void 0){if(d===a.l)throw Error("Cyclic dependency when requiring: "+c);return d===a.p?void 0:d===a.n?null:d}if(!a.g[c])throw Error("Module not found: "+
c);b[c]=a.l;b[c]=a.g[c]();return b[c]===void 0?b[c]=a.p:b[c]===null?b[c]=a.n:b[c]};a.c=[{}];a.b=a.c[0];a.R=function(){a.c.push({});a.b=a.c[a.c.length-1];a.e++};a.Q=function(){if(a.c.length===1)throw Error("Cannot discard the application modules cache.");a.c.pop();var b=a.i(a.f),c;for(c in b)a.v(c);for(c in a.b)(b=a.b[c])&&typeof b.q==="function"&&b.q();a.b=a.c[a.c.length-1];a.e++};a.D=function(){var b=[],c;for(c in a.b)a.b[c]!==-1&&b.push(c);return b};a.S=function(b,c){if(a.h.test(b))throw Error('Module name is required not to start with "?!".');
var d=a.b[b];a.b[b]=c;a.e++;return d};a.i=function(b){if(!a.h.test(b))throw Error('Namespace is required to start with "?!".');b in a.b||(a.b[b]={});return a.b[b]};var f=window.k;a.P=function(){if(window.k===a)window.k=f;return a};a.f="?!globals";a.T=function(b,c){var d=a.i(a.f);if(b in d)throw Error("Cannot set_global under duplicated name: "+b);d[b]=window[b];return window[b]=c};a.v=function(b){var c=a.i(a.f);if(!(b in c))throw Error("Cannot unset_global from unexisting name: "+b);window[b]=c[b];
delete c[b]};a.w={};a.C=function(b){b in a.o||(a.o[b]={});return a.o[b]};a.H=function(a){return typeof a==="boolean"||a&&a.toString()==="[object Boolean]"};a.K=function(a){return typeof a==="number"||a&&a.toString()==="[object Number]"};a.N=function(a){return typeof a==="string"||a&&a.toString()==="[object String]"};a.J=function(a){return typeof a==="function"||a&&a.toString()==="[object Function]"};a.G=function(a){return Array.isArray(a)};a.L=function(a){return typeof a==="number"||a&&a.toString()===
"[object Object]"};a.I=function(a){return a instanceof Date};a.M=function(a){return a instanceof RegExp};a.random=function(a){return a?Math.random()*a<<0:Math.random()};return a}();g.d("fierry/class",function(){return function(){function a(){}a.name="Xxx";return a}()});g.d("fierry/app",function(){console.log(g.a("fierry/math")().add(1,12))});
g.d("fierry-example/app",function(){var a=g.a("fierry/math"),f=g.j("fierry/class");console.log("Working example project 12");console.log(a().add(Math.random(),10));new f;console.log("hello")});g.d("fierry/math",function(){console.log("Loading math package");return{add:function(a,f){return a+f}}});
g.d("fierry/main_area:example",function(){var a=g.a("/fierry/view/roots"),f=g.j("/fierry/view/action"),b=g.a("/fierry/dom/p"),c=g.a("/fierry/dom/div"),d=g.a("/fierry/dom/body");return a().execute("body",d(),function(){arr=[];arr.push(new f("div","aa",this,c(),function(){},function(){var a;a=[];a.push(new f("p","aa",this,b(),e("Hello World!"),function(){return a=[]}));return a}));return arr})});
g.d("fierry/main_area:main_area",function(){function a(){arr=[];arr.push(new b("div","aa",this,l(),function(){},function(){var a;a=[];a.push(new b("tag","ab",this,h(),e("main-area unique"),function(){return a=[]}));a.push(new b("div","aa",this,l(),function(){},function(){var f,i,j;a=[];a.push(new b("p","aa",this,d(),e("Hello world"),function(){a=[];a.push(new b("tag","aa",this,h(),e("title"),function(){return a=[]}));return a}));a.push(new b("p","ab",this,d(),e("Here is some additional info"),function(){a=
[];a.push(new b("tag","aa",this,h(),e("desc"),function(){return a=[]}));return a}));a.push(new b("p","ac",this,d(),e("29.08.2011"),function(){return a=[]}));user.F!=null&&a.push(new b("p","ad",this,d(),e("Hello worldthat: I'm anything- I have to come see u!"),function(){return a=[]}));for(f=i=0,j=user.A.length;0<=j?i<=j:i>=j;f=0<=j?++i:--i)a.push(new b("p","ae"+c.u(f)+"aa",this,d(),function(){return f.name},function(){a=[];a.push(new b("tag","aa",this,h(),e("name"),function(){return a=[]}));return a})),
a.push(new b("p","ae"+c.u(f)+"ab",this,d(),function(){return f.B()},function(){a=[];a.push(new b("tag","aa",this,h(),e("desc"),function(){return a=[]}));return a}));return a}));return a}));arr.push(new b("div","ab",this,l(),function(){},function(){var a;a=[];a.push(new b("p","aa",this,d(),function(){return logged>0?"Logged":"Unlogged"},function(){return a=[]}));a.push(new b("p","ab",this,d(),function(){return user.name},function(){return a=[]}));user.O&&a.push(new b("p","ac",this,d(),e("goodbye"),
function(){return a=[]}));return a}));return arr}var f=g.a("/fierry/view/roots"),b=g.j("/fierry/view/action"),c=g.a("/source/Math"),d=g.a("/fierry/dom/p"),l=g.a("/fierry/dom/div"),h=g.a("/fierry/dom/tag"),m=g.a("/pfc-fierry/dom/body");return function(){return f().z("pfc-body",m(),a)}});g.t();