function e(a){return function(){return a}}
var g=function(){var a={g:{},s:{},h:/^\?!/,d:0};a.e=function(b,c){if(a.h.test(b))throw Error('Module name is required not to start with "?!".');a.g[b]=c};a.r=-1;a.b=function(b){var c,d=a.r;return function(){if(d<a.d)d=a.d,c=a.l(a.a,b);return c}};a.p=function(){return a.l(a.s,"/fierry/view/action")};a.t=function(){a.b("fierry/app")()};a.k={};a.o={};a.m={};a.l=function(b,c){var d=b[c];if(d!==void 0){if(d===a.k)throw Error("Cyclic dependency when requiring: "+c);return d===a.o?void 0:d===a.m?null:d}if(!a.g[c])throw Error("Module not found: "+
c);b[c]=a.k;b[c]=a.g[c]();return b[c]===void 0?b[c]=a.o:b[c]===null?b[c]=a.m:b[c]};a.c=[{}];a.a=a.c[0];a.R=function(){a.c.push({});a.a=a.c[a.c.length-1];a.d++};a.Q=function(){if(a.c.length===1)throw Error("Cannot discard the application modules cache.");a.c.pop();var b=a.i(a.f),c;for(c in b)a.v(c);for(c in a.a)(b=a.a[c])&&typeof b.q==="function"&&b.q();a.a=a.c[a.c.length-1];a.d++};a.D=function(){var b=[],c;for(c in a.a)a.a[c]!==-1&&b.push(c);return b};a.S=function(b,c){if(a.h.test(b))throw Error('Module name is required not to start with "?!".');
var d=a.a[b];a.a[b]=c;a.d++;return d};a.i=function(b){if(!a.h.test(b))throw Error('Namespace is required to start with "?!".');b in a.a||(a.a[b]={});return a.a[b]};var f=window.j;a.P=function(){if(window.j===a)window.j=f;return a};a.f="?!globals";a.T=function(b,c){var d=a.i(a.f);if(b in d)throw Error("Cannot set_global under duplicated name: "+b);d[b]=window[b];return window[b]=c};a.v=function(b){var c=a.i(a.f);if(!(b in c))throw Error("Cannot unset_global from unexisting name: "+b);window[b]=c[b];
delete c[b]};a.w={};a.C=function(b){b in a.n||(a.n[b]={});return a.n[b]};a.H=function(a){return typeof a==="boolean"||a&&a.toString()==="[object Boolean]"};a.K=function(a){return typeof a==="number"||a&&a.toString()==="[object Number]"};a.N=function(a){return typeof a==="string"||a&&a.toString()==="[object String]"};a.J=function(a){return typeof a==="function"||a&&a.toString()==="[object Function]"};a.G=function(a){return Array.isArray(a)};a.L=function(a){return typeof a==="number"||a&&a.toString()===
"[object Object]"};a.I=function(a){return a instanceof Date};a.M=function(a){return a instanceof RegExp};a.random=function(a){return a?Math.random()*a<<0:Math.random()};return a}();g.e("fierry/class",function(){return function(){function a(){}a.name="Xxx";return a}()});g.e("fierry/app",function(){console.log(g.b("fierry/math")().add(1,12))});g.e("fierry/math",function(){console.log("Loading math package");return{add:function(a,f){return a+f}}});
g.e("fierry/main_area:example",function(){var a=g.b("/fierry/view/roots"),f=g.p(),b=g.b("/fierry/dom/p"),c=g.b("/fierry/dom/div"),d=g.b("/fierry/dom/body");return a().execute("body",d(),function(){arr=[];arr.push(new f("div","aa",this,c(),function(){},function(){var a;a=[];a.push(new f("p","aa",this,b(),e("Hello World!"),function(){return a=[]}));return a}));return arr})});
g.e("fierry/main_area:main_area",function(){function a(){arr=[];arr.push(new b("div","aa",this,l(),function(){},function(){var a;a=[];a.push(new b("tag","ab",this,h(),e("main-area unique"),function(){return a=[]}));a.push(new b("div","aa",this,l(),function(){},function(){var f,i,k;a=[];a.push(new b("p","aa",this,d(),e("Hello world"),function(){a=[];a.push(new b("tag","aa",this,h(),e("title"),function(){return a=[]}));return a}));a.push(new b("p","ab",this,d(),e("Here is some additional info"),function(){a=
[];a.push(new b("tag","aa",this,h(),e("desc"),function(){return a=[]}));return a}));a.push(new b("p","ac",this,d(),e("29.08.2011"),function(){return a=[]}));user.F!=null&&a.push(new b("p","ad",this,d(),e("Hello worldthat: I'm anything- I have to come see u!"),function(){return a=[]}));for(f=i=0,k=user.A.length;0<=k?i<=k:i>=k;f=0<=k?++i:--i)a.push(new b("p","ae"+c.u(f)+"aa",this,d(),function(){return f.name},function(){a=[];a.push(new b("tag","aa",this,h(),e("name"),function(){return a=[]}));return a})),
a.push(new b("p","ae"+c.u(f)+"ab",this,d(),function(){return f.B()},function(){a=[];a.push(new b("tag","aa",this,h(),e("desc"),function(){return a=[]}));return a}));return a}));return a}));arr.push(new b("div","ab",this,l(),function(){},function(){var a;a=[];a.push(new b("p","aa",this,d(),function(){return logged>0?"Logged":"Unlogged"},function(){return a=[]}));a.push(new b("p","ab",this,d(),function(){return user.name},function(){return a=[]}));user.O&&a.push(new b("p","ac",this,d(),e("goodbye"),
function(){return a=[]}));return a}));return arr}var f=g.b("/fierry/view/roots"),b=g.p(),c=g.b("/source/Math"),d=g.b("/fierry/dom/p"),l=g.b("/fierry/dom/div"),h=g.b("/fierry/dom/tag"),m=g.b("/pfc-fierry/dom/body");return function(){return f().z("pfc-body",m(),a)}});g.t();